title: KS1StorytellingTraining_Session2_Part2_GBICi1b
hero_image: images/banner.png
description: KS1StorytellingTraining_Session2_Part2_GBICi1b description
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
