title: "Session 3: KS1 'Storytelling' training – Investigating resources"
hero_image: images/introduction3.png
description:  Session 3 of training for teachers introduces the remainder of the resources for KS1 Storytelling GBICi1b trial through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: ScratchJr tasks
  - title: "Task 3: Drawing ideas"
  - title: "Task 4: ScratchJr interface and blocks"
  - title: "Task 5: ScratchJr blocks: Questions and answers"
  - title: "Task 6: Drawing in ScratchJr"
  - title: "Task 7: Sharing projects"
  - title: "Task 8: Post-training webinar"
  - title: "Task 9: Completion survey"
  
